copy /Y /B .\output\histoire\methode.html           ..\..\..\dgx\histoire\methode.html
copy /Y /B .\output\histoire\bibliographie.html     ..\..\..\dgx\histoire\bibliographie.html
copy /Y /B .\output\histoire\france19eme.html       ..\..\..\dgx\histoire\france19eme.html
copy /Y /B .\output\informatique\hamill.html        ..\..\..\dgx\informatique\hamill.html
copy /Y /B .\output\informatique\json.html          ..\..\..\dgx\informatique\json.html
copy /Y /B .\output\informatique\tools_langs.html   ..\..\..\dgx\informatique\tools_langs.html
copy /Y /B .\output\passetemps\pres_favoris.html    ..\..\..\dgx\passetemps\pres_favoris.html
copy /Y /B .\output\passetemps\pres_jeux.html       ..\..\..\dgx\passetemps\pres_jeux.html
copy /Y /B .\output\passetemps\pres_jeuxvideo.html  ..\..\..\dgx\passetemps\pres_jeuxvideo.html
copy /Y /B .\output\passetemps\tech_dialogues.html  ..\..\..\dgx\passetemps\tech_dialogues.html
copy /Y /B .\output\index.html                      ..\..\..\dgx\index.html
copy /Y /B .\output\plan.html                       ..\..\..\dgx\plan.html
copy /Y /B .\output\blog.html                       ..\..\..\dgx\blog.html
