SCREEN 7
secteur = 1
SELECT CASE secteur
CASE IS = 1
        xmax = 10
        xmin = 2
        ymax = 20
        ymin = 10
'CASE IS = 2
'        xmax =
'        xmin =
'        ymax =
'        ymin =
'CASE IS = 3
'        xmax =
'        xmin =
'        ymax =
'        ymin =
'CASE IS = 4
'        xmax =
'        xmin =
'        ymax =
'        ymin =
'CASE IS = 5
'        xmax =
'        xmin =
'        ymax =
'        ymin =
'CASE IS = 6
'        xmax =
'        xmin =
'        ymax =
'        ymin =
'CASE IS = 7
'        xmax =
'        xmin =
'        ymax =
'        ymin =
END SELECT
LINE (xmax, ymax)-(xmin, ymin), , B


